name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.7
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: test_pumping
          MARIADB_USER: testuser
          MARIADB_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -utestuser -ptestpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment variables (testuser/testpass)
        run: |
          echo "DB_USERNAME=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpass" >> $GITHUB_ENV
          echo "FILE_UPLOAD_DIR=/tmp/uploads" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build
        env:
          DB_USERNAME: testuser
          DB_PASSWORD: testpass
          FILE_UPLOAD_DIR: /tmp/uploads

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/pumping-*.jar"
          target: "/home/ubuntu/app/"

      - name: SSH Restart App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'pumping-.*\.jar' || true
            nohup java -jar /home/ubuntu/app/pumping-*.jar \
              --spring.config.location=file:/home/ubuntu/app/config/ \
              --spring.profiles.active=prod \
              > /home/ubuntu/app/logs/pumping.log 2>&1 &
